server:
  port: 8765

spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        - id: Microservice
          uri: http://localhost:8081/
          predicates:
            - Path=/service/**
      discovery:
        locator:
          lower-case-service-id: true
#  main:
#    web-application-type: reactive